# Doctrine Configuration
doctrine:
    dbal:
        url:                '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true