# Framework Configuration
framework:
    secret:             "%env(string:APP_SECRET)%"
    router:
        default_uri:    "%env(string:APP_URI)%"
        resource:       "%kernel.project_dir%/tests/config/routing.yml"
    test:               ~
    profiler: { only_exceptions: false }
