
###############################################################################
# Test Configuration for Splash Bundle
splash:
    connections:

        node1:
            id:                 ThisIsFaker1WsId
            key:                ThisIsNotASecretKeyForFaker
            name:               Serveur 1 (Faker)

        node2:
            id:                 ThisIsFaker2WsId
            key:                ThisIsNotASecretKeyForFaker
            name:               Serveur 2 (Faker)